name: release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Update package version
        run: npm versioning

      - name: Commit and push package.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Update package version"
          TARGET_COMMITISH=$(jq -r '.release.target_commitish' $GITHUB_EVENT_PATH)
          git push origin HEAD:${TARGET_COMMITISH}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
